CREATE TABLE IF NOT EXISTS users(
 id SERIAL PRIMARY KEY, staff_code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, mobile TEXT,
 username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL,
 role TEXT NOT NULL DEFAULT 'teacher' CHECK(role IN('admin','teacher')),
 active BOOLEAN NOT NULL DEFAULT true, must_change BOOLEAN NOT NULL DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attendance(
 id SERIAL PRIMARY KEY, user_id INT NOT NULL REFERENCES users(id), date DATE NOT NULL,
 in_time TIMESTAMPTZ, out_time TIMESTAMPTZ, status TEXT,
 in_lat DOUBLE PRECISION, in_lng DOUBLE PRECISION, in_acc REAL, in_qr BOOLEAN NOT NULL DEFAULT false,
 out_lat DOUBLE PRECISION, out_lng DOUBLE PRECISION, out_acc REAL, out_qr BOOLEAN NOT NULL DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(user_id,date));
CREATE INDEX IF NOT EXISTS attendance_date_idx ON attendance(date);
CREATE TABLE IF NOT EXISTS notifications(id SERIAL PRIMARY KEY, msg TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs(id SERIAL PRIMARY KEY, user_id INT, action TEXT NOT NULL, detail TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
